# Generated by Django 5.0 on 2025-11-16 23:23

import apps.auths.validators
import django.contrib.auth.password_validation
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('email', models.EmailField(db_index=True, help_text='User`s email address', max_length=150, unique=True, validators=[apps.auths.validators.validatate_email_domain], verbose_name='Email address')),
                ('full_name', models.CharField(help_text='User`s full name', max_length=150, verbose_name='Full name')),
                ('password', models.CharField(help_text="User's hash representation of the password", max_length=254, validators=[django.contrib.auth.password_validation.validate_password], verbose_name='Password')),
                ('phone', models.CharField(blank=True, help_text='The phone number must be from 11.', max_length=11, validators=[apps.auths.validators.validate_phone], verbose_name='Phone number')),
                ('country', models.CharField(blank=True, help_text='Country where the user lives', max_length=255, verbose_name='Country')),
                ('department', models.CharField(blank=True, help_text='User`s department (e.g., IT, HR, Sales, Finance)', max_length=255, verbose_name='Department')),
                ('role', models.CharField(blank=True, choices=[('admin', 'Admin'), ('manager', 'Manager'), ('employee', 'Employee')], default='employee', help_text='User`s role in company', max_length=255, verbose_name='Role')),
                ('birth_date', models.DateField(blank=True, help_text='User`s date of birth', null=True, verbose_name='Birth Date')),
                ('salary', models.IntegerField(blank=True, help_text='User`s salary per month', null=True, verbose_name='Salary')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this user account is active', verbose_name='Active')),
                ('is_staff', models.BooleanField(default=False, help_text='Defines if user can access the admin panel', verbose_name='Staff Status')),
                ('data_joined', models.DateTimeField(default=django.utils.timezone.now, help_text='The date when the user registered', verbose_name='Data Joined')),
                ('last_login', models.DateTimeField(blank=True, help_text='Last login timestamp', null=True, verbose_name='Last login')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Custom User',
                'verbose_name_plural': 'Custom Users',
                'ordering': ['-created_at'],
            },
        ),
    ]
