# Generated by Django 5.0 on 2025-11-17 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='city',
            field=models.CharField(blank=True, help_text='City where the user lives', max_length=255, verbose_name='City'),
        ),
    ]
